name: "Download External Rulesets"

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"

jobs:
  download_file:
    name: Download External Rulesets
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Download external files
        run: |
            curl https://https://a.dove.isdumb.one/pihole.txt -o External/adobe.conf
            curl https://jsdelivr.kemono.de/gh/Loyalsoldier/surge-rules@release/gfw.txt -o External/gfw.conf
            
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          token: ${{ secrets.PAT }}
