name: "Download External Rulesets"

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"
  push:

jobs:
  download_file:
    name: Download External Rulesets
    runs-on: ubuntu-latest
    steps:
      - name: Check out current commit
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Download external files
        run: |
            curl https://a.dove.isdumb.one/pihole.txt > Artifacts/External/adobe.conf
            curl https://raw.githubusercontent.com/Loyalsoldier/surge-rules/refs/heads/release/gfw.txt > Artifacts/External/gfw.conf
            curl https://raw.githubusercontent.com/misakaio/chnroutes2/refs/heads/master/chnroutes.txt > Artifacts/External/direct_ip.conf
            curl https://core.telegram.org/resources/cidr.txt > Artifacts/External/telegram_ip.conf

      - name: Generate new files
        run: |
            chmod a+x clash_domainset.sh
            ./clash_domainset.sh Artifacts/External Artifacts/External/Clash conf
            ./clash_domainset.sh Artifacts/Snippet/Domainset Artifacts/Snippet/Domainset/Clash conf

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          token: ${{ secrets.PAT }}
